from __future__ import annotations

from typing import Any


THEME_PRESETS: list[dict[str, Any]] = [
    {
        "id": "sao_dem",
        "name": "Sao đêm",
        "description": "Nền tối, ánh sao lấp lánh nhẹ.",
        "tokens": {
            "bg": "#090a1a",
            "bg2": "#111433",
            "surface": "#11162d",
            "surface_alt": "#151f42",
            "text": "#eaf2ff",
            "muted": "#8ca3d4",
            "accent": "#77b8ff",
            "glow": "#9fd0ff",
            "particle": "#ffffff",
        },
        "export_tokens": {
            "bg": "#090a1a",
            "bg_elev": "#111433",
            "surface": "#11162d",
            "surface_strong": "#151f42",
            "text": "#eaf2ff",
            "muted": "#8ca3d4",
            "border": "rgba(140,163,212,.16)",
            "shadow": "0 28px 62px rgba(0,0,0,.34)",
            "accent": "#77b8ff",
            "accent_soft": "rgba(119,184,255,.16)",
        },
        "effect": "stars",
    },
    {
        "id": "hong_phan",
        "name": "Hồng phấn",
        "description": "Tông pastel mềm, glow dịu mắt.",
        "tokens": {
            "bg": "#2d1022",
            "bg2": "#4a1f3b",
            "surface": "#4f2242",
            "surface_alt": "#613053",
            "text": "#ffeef8",
            "muted": "#f3bdd8",
            "accent": "#ff7fba",
            "glow": "#ff9bd0",
            "particle": "#ffd3ea",
        },
        "export_tokens": {
            "bg": "#2d1022",
            "bg_elev": "#4a1f3b",
            "surface": "#4f2242",
            "surface_strong": "#613053",
            "text": "#ffeef8",
            "muted": "#f3bdd8",
            "border": "rgba(255,211,234,.16)",
            "shadow": "0 28px 64px rgba(35,7,22,.32)",
            "accent": "#ff7fba",
            "accent_soft": "rgba(255,127,186,.18)",
        },
        "effect": "sparkle",
    },
    {
        "id": "xanh_da_troi",
        "name": "Xanh da trời",
        "description": "Mát mắt, gradient trong trẻo.",
        "tokens": {
            "bg": "#092039",
            "bg2": "#0e4d77",
            "surface": "#0f3858",
            "surface_alt": "#15527a",
            "text": "#eaf8ff",
            "muted": "#a8d5ee",
            "accent": "#69d3ff",
            "glow": "#90e4ff",
            "particle": "#def8ff",
        },
        "export_tokens": {
            "bg": "#092039",
            "bg_elev": "#0e4d77",
            "surface": "#0f3858",
            "surface_strong": "#15527a",
            "text": "#eaf8ff",
            "muted": "#a8d5ee",
            "border": "rgba(173,225,247,.16)",
            "shadow": "0 28px 66px rgba(2,17,33,.3)",
            "accent": "#69d3ff",
            "accent_soft": "rgba(105,211,255,.18)",
        },
        "effect": "bubbles",
    },
    {
        "id": "la_vang",
        "name": "Lá vàng",
        "description": "Ấm áp mùa thu, hạt vàng bay nhẹ.",
        "tokens": {
            "bg": "#2c1707",
            "bg2": "#673512",
            "surface": "#553018",
            "surface_alt": "#70401f",
            "text": "#fff3de",
            "muted": "#e7c595",
            "accent": "#ffbe55",
            "glow": "#ffd27a",
            "particle": "#ffe6b8",
        },
        "export_tokens": {
            "bg": "#2c1707",
            "bg_elev": "#673512",
            "surface": "#553018",
            "surface_strong": "#70401f",
            "text": "#fff3de",
            "muted": "#e7c595",
            "border": "rgba(255,230,184,.16)",
            "shadow": "0 28px 64px rgba(38,17,4,.32)",
            "accent": "#ffbe55",
            "accent_soft": "rgba(255,190,85,.18)",
        },
        "effect": "leaves",
    },
    {
        "id": "tuyet_trang",
        "name": "Tuyết trắng",
        "description": "Nền sáng lạnh, tuyết mịn rơi nhẹ.",
        "tokens": {
            "bg": "#e4edf9",
            "bg2": "#ffffff",
            "surface": "#f7fbff",
            "surface_alt": "#ecf4ff",
            "text": "#102440",
            "muted": "#4b6382",
            "accent": "#6ab7ff",
            "glow": "#9bcfff",
            "particle": "#ffffff",
        },
        "export_tokens": {
            "bg": "#e4edf9",
            "bg_elev": "#ffffff",
            "surface": "#f7fbff",
            "surface_strong": "#ecf4ff",
            "text": "#102440",
            "muted": "#4b6382",
            "border": "rgba(75,99,130,.18)",
            "shadow": "0 22px 46px rgba(84,122,170,.14)",
            "accent": "#6ab7ff",
            "accent_soft": "rgba(106,183,255,.18)",
        },
        "effect": "snow",
    },
    {
        "id": "xanh_nhat",
        "name": "Xanh nhạt",
        "description": "Pastel xanh baby, sáng và dịu.",
        "tokens": {
            "bg": "#c8eaf5",
            "bg2": "#eaf8fd",
            "surface": "#f4fcff",
            "surface_alt": "#e4f3f9",
            "text": "#173746",
            "muted": "#5e7d8c",
            "accent": "#46a9d5",
            "glow": "#9fdff4",
            "particle": "#ffffff",
        },
        "export_tokens": {
            "bg": "#c8eaf5",
            "bg_elev": "#eaf8fd",
            "surface": "#f4fcff",
            "surface_strong": "#e4f3f9",
            "text": "#173746",
            "muted": "#5e7d8c",
            "border": "rgba(23,55,70,.14)",
            "shadow": "0 22px 46px rgba(74,135,166,.14)",
            "accent": "#46a9d5",
            "accent_soft": "rgba(70,169,213,.18)",
        },
        "effect": "bubbles",
    },
    {
        "id": "hong_nhat",
        "name": "Hồng nhạt",
        "description": "Pastel hồng phấn sáng, mềm và êm.",
        "tokens": {
            "bg": "#f4d4e2",
            "bg2": "#fff1f7",
            "surface": "#fff8fb",
            "surface_alt": "#fdebf3",
            "text": "#4b2234",
            "muted": "#8c6274",
            "accent": "#df7eab",
            "glow": "#f3b6d0",
            "particle": "#fffafd",
        },
        "export_tokens": {
            "bg": "#f4d4e2",
            "bg_elev": "#fff1f7",
            "surface": "#fff8fb",
            "surface_strong": "#fdebf3",
            "text": "#4b2234",
            "muted": "#8c6274",
            "border": "rgba(75,34,52,.14)",
            "shadow": "0 22px 46px rgba(171,103,136,.14)",
            "accent": "#df7eab",
            "accent_soft": "rgba(223,126,171,.18)",
        },
        "effect": "sparkle",
    },
    {
        "id": "mint_m0602",
        "name": "Xanh bạc hà",
        "description": "Nền mint sáng, dịu mắt khi đọc lâu.",
        "tokens": {
            "bg": "#e0f6e6",
            "bg2": "#f5fff8",
            "surface": "#f8fffa",
            "surface_alt": "#d6f1df",
            "text": "#17352a",
            "muted": "#5d7b6f",
            "accent": "#3f9a70",
            "glow": "#a7e2c0",
            "particle": "#ffffff",
        },
        "export_tokens": {
            "bg": "#e0f6e6",
            "bg_elev": "#f5fff8",
            "surface": "#f8fffa",
            "surface_strong": "#d6f1df",
            "text": "#17352a",
            "muted": "#5d7b6f",
            "border": "rgba(23,53,42,.14)",
            "shadow": "0 22px 46px rgba(87,150,118,.13)",
            "accent": "#3f9a70",
            "accent_soft": "rgba(63,154,112,.16)",
        },
        "effect": "snow",
    },
    {
        "id": "tim_f5e1fd",
        "name": "Tím oải hương",
        "description": "Nền tím nhạt, sáng và ít chói.",
        "tokens": {
            "bg": "#f5e1fd",
            "bg2": "#fff7ff",
            "surface": "#fffaff",
            "surface_alt": "#efd3fa",
            "text": "#3d2249",
            "muted": "#7a6383",
            "accent": "#9b5fbd",
            "glow": "#d8a9ee",
            "particle": "#ffffff",
        },
        "export_tokens": {
            "bg": "#f5e1fd",
            "bg_elev": "#fff7ff",
            "surface": "#fffaff",
            "surface_strong": "#efd3fa",
            "text": "#3d2249",
            "muted": "#7a6383",
            "border": "rgba(61,34,73,.14)",
            "shadow": "0 22px 46px rgba(149,91,178,.13)",
            "accent": "#9b5fbd",
            "accent_soft": "rgba(155,95,189,.16)",
        },
        "effect": "sparkle",
    },
    {
        "id": "paper",
        "name": "Giấy sáng",
        "description": "Tông giấy sáng, sạch và thoáng.",
        "tokens": {
            "bg": "#f5f0e8",
            "bg2": "#fffdf8",
            "surface": "#fffaf1",
            "surface_alt": "#ffffff",
            "text": "#1f1a17",
            "muted": "#6d6259",
            "accent": "#99572a",
            "glow": "#dbc4a6",
            "particle": "#fff8ef",
        },
        "export_tokens": {
            "bg": "#f5f0e8",
            "bg_elev": "#fffdf8",
            "surface": "#fffaf1",
            "surface_strong": "#ffffff",
            "text": "#1f1a17",
            "muted": "#6d6259",
            "border": "rgba(73,54,38,.14)",
            "shadow": "0 24px 48px rgba(46,31,20,.12)",
            "accent": "#99572a",
            "accent_soft": "rgba(153,87,42,.14)",
        },
        "effect": "snow",
    },
    {
        "id": "sepia",
        "name": "Sepia cổ điển",
        "description": "Ấm, hơi cổ, giống giấy cũ.",
        "tokens": {
            "bg": "#efe1c8",
            "bg2": "#fbf1dc",
            "surface": "#fff7ea",
            "surface_alt": "#fffaf2",
            "text": "#261d14",
            "muted": "#73604d",
            "accent": "#9b5a20",
            "glow": "#d8bb90",
            "particle": "#fff3de",
        },
        "export_tokens": {
            "bg": "#efe1c8",
            "bg_elev": "#fbf1dc",
            "surface": "#fff7ea",
            "surface_strong": "#fffaf2",
            "text": "#261d14",
            "muted": "#73604d",
            "border": "rgba(71,48,22,.18)",
            "shadow": "0 24px 54px rgba(69,44,18,.15)",
            "accent": "#9b5a20",
            "accent_soft": "rgba(155,90,32,.16)",
        },
        "effect": "leaves",
    },
    {
        "id": "graphite",
        "name": "Than chì",
        "description": "Tối xám hiện đại, trung tính và sạch.",
        "tokens": {
            "bg": "#181c22",
            "bg2": "#20262f",
            "surface": "#242c36",
            "surface_alt": "#2a3440",
            "text": "#eef2f7",
            "muted": "#9aa8ba",
            "accent": "#7fc2ff",
            "glow": "#9fd3ff",
            "particle": "#d9ecff",
        },
        "export_tokens": {
            "bg": "#181c22",
            "bg_elev": "#20262f",
            "surface": "#242c36",
            "surface_strong": "#2a3440",
            "text": "#eef2f7",
            "muted": "#9aa8ba",
            "border": "rgba(178,194,214,.16)",
            "shadow": "0 26px 60px rgba(0,0,0,.32)",
            "accent": "#7fc2ff",
            "accent_soft": "rgba(127,194,255,.16)",
        },
        "effect": "stars",
    },
    {
        "id": "midnight",
        "name": "Nửa đêm",
        "description": "Tông đêm sâu, tương phản cao hơn.",
        "tokens": {
            "bg": "#0f1217",
            "bg2": "#161b22",
            "surface": "#1d2430",
            "surface_alt": "#252f3d",
            "text": "#f4f7fb",
            "muted": "#9caabd",
            "accent": "#9fd3ff",
            "glow": "#c1e0ff",
            "particle": "#eef6ff",
        },
        "export_tokens": {
            "bg": "#0f1217",
            "bg_elev": "#161b22",
            "surface": "#1d2430",
            "surface_strong": "#252f3d",
            "text": "#f4f7fb",
            "muted": "#9caabd",
            "border": "rgba(185,202,224,.14)",
            "shadow": "0 30px 70px rgba(0,0,0,.4)",
            "accent": "#9fd3ff",
            "accent_soft": "rgba(159,211,255,.16)",
        },
        "effect": "stars",
    },
]


EXPORT_THEME_PRESETS: list[dict[str, Any]] = [
    {
        "id": str(item.get("id") or "").strip(),
        "name": str(item.get("name") or "").strip(),
        "tokens": dict(item.get("export_tokens") or {}),
    }
    for item in THEME_PRESETS
    if str(item.get("id") or "").strip() and isinstance(item.get("export_tokens"), dict)
]
